package utility

object Constants {
  val WORD_WIDTH = 32
  val HALF_WIDTH = 16
  val BYTE_WIDTH = 8
  
  val INST_WIDTH = 32
  val ADDR_WIDTH = 32

  val BYTES_PER_INST = INST_WIDTH / BYTE_WIDTH
  val BYTES_PER_WORD = WORD_WIDTH / BYTE_WIDTH
  val BYTES_PER_HALF = HALF_WIDTH / BYTE_WIDTH
  val BYTES_PER_BYTE = BYTE_WIDTH / BYTE_WIDTH
}